spring.application.name=springbootappmongo
spring.data.mongodb.uri=mongodb+srv://admin:root1234@mern-booking-app-db.456h2.mongodb.net/testdb
server.port=8080

# Swagger path (optional)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html